/**
 * Azure AI Speech (Fast Transcription / MAI-Transcribe-2) transcription handler.
 *
 * Extracted from audioTranscription.ts to keep that dispatcher under the
 * file-size cap; behavior is unchanged. Shares the multipart/error helpers
 * with the dispatcher the same way openrouterTranscription.ts does.
 */
import { CORS_HEADERS } from "../utils/cors.ts";
import type { AudioProvider } from "../config/audioRegistry.ts";
import { buildAuthHeaders } from "../config/registryUtils.ts";
import { errorResponse } from "../utils/error.ts";
import { isAzureMaiNativeMime, normalizeForAzureMai } from "./azureMaiAudioNormalization.ts";
import {
  buildMultipartBody,
  upstreamErrorResponse,
  type TranscriptionCredentials,
} from "./audioTranscription.ts";

/**
 * O360-specific technical vocabulary hints for Azure's phraseList (Fast
 * Transcription API, api-version 2025-10-15+ — see
 * https://learn.microsoft.com/azure/ai-services/speech-service/improve-accuracy-phrase-list).
 * A single flat list, applied to every Azure request regardless of the
 * request's own language — deliberately NOT a per-locale/per-caller lookup
 * table. If this needs to vary per deployment later, that's a config knob,
 * not a bigger data structure.
 */
export const AZURE_PHRASE_HINTS = [
  "OpenTelemetry",
  "OTel",
  "OTLP",
  "OpenTelemetry Collector",
  "ClickHouse",
  "HyperDX",
  "Prometheus",
  "Grafana",
  "Kubernetes",
  "Fluent Bit",
  "TraceId",
  "SpanId",
  "traceparent",
  "cardinalidade",
  "telemetria",
  "observabilidade",
  "SRE",
  "DevOps",
  "Docker",
  "Terraform",
  "GitHub",
  "Coder",
  "OmniRoute",
];

const AZURE_DEFAULT_LOCALE = "pt-BR";
const AZURE_REQUEST_TIMEOUT_MS = 30_000;
// 25 MiB comfortably covers a 120s webm/opus voice recording at typical
// voice bitrates (well under 1 MiB) with generous headroom — matches the
// cap already enforced upstream by the Coder proxy, kept in sync
// deliberately rather than trusting only the caller's own limit.
const AZURE_MAX_AUDIO_BYTES = 25 * 1024 * 1024;
// What real browser MediaRecorder output + the handful of container formats
// Azure's Fast Transcription API documents support actually look like —
// not Azure's full supported-format list (WAV, MP3, OPUS/OGG, FLAC, WMA,
// AAC, ALAW/MULAW-in-WAV, AMR, WebM, SPEEX): this is a dictation-recording
// upload, not a general media-file ingestion endpoint. Anything here that
// isn't in AZURE_MAI_NATIVE_MIME_PREFIXES is normalized (transcoded) before
// it reaches Azure — see normalizeForAzureMai().
const AZURE_ALLOWED_MIME_PREFIXES = [
  "audio/webm",
  "audio/ogg",
  "audio/wav",
  "audio/mp4",
  "audio/mpeg",
  "audio/flac",
];

/**
 * Handle Azure AI Speech transcription (Fast Transcription API).
 *
 * Request shape is verified directly against Microsoft's own docs
 * (fast-transcription-create), not assumed — the OLDER "speech to text REST
 * API for short audio" surface only accepts wav/pcm or ogg/opus, which would
 * have forced client-side transcoding for Chrome/Edge's native MediaRecorder
 * output (audio/webm;codecs=opus).
 *
 * IMPORTANT — WebM support does NOT extend to the enhancedMode/MAI-Transcribe-2
 * path used here. The generic (baseline) Fast Transcription surface documents
 * WebM as a supported container, but production testing (2026-09-09) proved
 * enhancedMode.model="MAI-Transcribe-2" rejects it: a real browser-recorded
 * audio/webm;codecs=opus upload returned a real Azure 400
 * ("invalid_audio" / "Format not recognised: Error opening <BytesIO>..."),
 * while byte-identical spoken content re-encoded as MP3 against the SAME
 * endpoint/model/credentials returned 200 with an exact transcript.
 * MAI-Transcribe-2's own documented input formats are WAV, MP3, and FLAC —
 * see normalizeForAzureMai() below, which transcodes anything else
 * (webm/ogg/mp4) to WAV before it ever reaches this function's request body.
 * Do not re-introduce a claim that WebM reaches Azure unchanged.
 *
 * Auth + endpoint: addressed via Azure's region-based endpoint
 * (https://{region}.api.cognitive.microsoft.com/...), authenticated purely
 * by the Ocp-Apim-Subscription-Key header — no custom subdomain is required
 * (custom subdomains are an optional, separate Azure feature this resource
 * does not have enabled; confirmed via a live test call against the real
 * provisioned resource). The region must be configured per-credential via
 * providerSpecificData (identical pattern to vertexMedia.ts's per-credential
 * region/project).
 *
 * Model: enhancedMode.model="MAI-Transcribe-2" (Microsoft's MAI transcription
 * model, surfaced as an LLM-based "enhanced mode" on this same endpoint).
 * This field is NOT present in Microsoft's own public docs — verified absent
 * from both the fast-transcription-create conceptual doc and the
 * autogenerated REST reference for this exact endpoint/api-version — but it
 * is real and server-validated: an unsupported model name is rejected with
 * a real 400 ("Requested MAI transcription model '<name>' is not
 * supported."), and MAI-Transcribe-2 is accepted. Selected after a real,
 * reproducible (3x, byte-identical) A/B/C test against production audio
 * showed it alone (not phraseList, not a biasingWeight field — which the
 * docs only expose via the SDK's real-time SetWeight() and which is
 * silently ignored by this REST endpoint, hence omitted here) took exact
 * recognition of 4 target technical terms from 0/4 to 4/4. Treat as
 * public-preview / undocumented: not guaranteed stable, not confirmed
 * covered by F0 pricing, and could change or be withdrawn without notice
 * in a future Azure API revision.
 *
 * Response shape is NOT { text } like Whisper — it's
 * { combinedPhrases: [{ text }, ...] } (one entry per detected channel/
 * speaker) — normalized here to the single { text } shape every other
 * provider in this file already returns. Verified against both the
 * baseline response shape (per-phrase word-level timestamps + confidence)
 * and MAI-Transcribe-2's response shape (single combined phrase, no word
 * timestamps, confidence 0) — combinedPhrases is present and consistent in
 * both, so no shape-specific branching is needed here.
 */
/** Validate the region credential + MIME/size bounds. Split out purely
 *  to keep handleAzureTranscription's own branching flat; no behavior change. */
function validateAzureUpload(
  file: Blob & { name?: unknown },
  credentials: TranscriptionCredentials | null
): { region: string } | { errorResponse: Response } {
  const region = credentials?.providerSpecificData?.region;
  if (typeof region !== "string" || !region.trim()) {
    return {
      errorResponse: errorResponse(
        400,
        'Azure Speech connection is missing providerSpecificData.region (the Speech resource\'s region, e.g. "eastus")'
      ),
    };
  }

  const uploadedType = (file.type || "").toLowerCase();
  if (!AZURE_ALLOWED_MIME_PREFIXES.some((prefix) => uploadedType.startsWith(prefix))) {
    return {
      errorResponse: errorResponse(
        400,
        `Unsupported audio content type "${file.type || "unknown"}" for Azure Speech. Allowed: ${AZURE_ALLOWED_MIME_PREFIXES.join(", ")}`
      ),
    };
  }
  if (file.size > AZURE_MAX_AUDIO_BYTES) {
    return {
      errorResponse: errorResponse(
        413,
        `Audio file too large (${file.size} bytes). Maximum is ${AZURE_MAX_AUDIO_BYTES} bytes.`
      ),
    };
  }

  return { region: region.trim() };
}

/** POST to Azure with a bounded timeout, mapping a thrown fetch error (timeout
 *  or network failure) to an already-built error Response. Split out purely
 *  to keep handleAzureTranscription's own branching flat; no behavior change. */
async function fetchAzureTranscription(
  url: string,
  headers: Record<string, string>,
  body: Uint8Array<ArrayBuffer>
): Promise<{ response: Response } | { errorResponse: Response }> {
  try {
    const response = await fetch(url, {
      method: "POST",
      headers,
      body,
      signal: AbortSignal.timeout(AZURE_REQUEST_TIMEOUT_MS),
    });
    return { response };
  } catch (err) {
    const isTimeout = err instanceof Error && err.name === "TimeoutError";
    return {
      errorResponse: errorResponse(
        isTimeout ? 504 : 502,
        isTimeout
          ? `Azure Speech request timed out after ${AZURE_REQUEST_TIMEOUT_MS}ms`
          : `Failed to reach Azure Speech: ${err instanceof Error ? err.message : "unknown error"}`
      ),
    };
  }
}

/** Parse a successful Azure response and normalize { combinedPhrases } to
 *  { text }. Split out purely to keep handleAzureTranscription's own
 *  branching flat; no behavior change. */
async function parseAzureTranscriptionResponse(res: Response): Promise<Response> {
  let data: unknown;
  try {
    data = await res.json();
  } catch {
    return errorResponse(502, "Azure Speech returned a response that was not valid JSON");
  }

  const phrases = (data as { combinedPhrases?: unknown })?.combinedPhrases;
  if (!Array.isArray(phrases)) {
    return errorResponse(
      502,
      "Azure Speech returned an unexpected response shape (missing combinedPhrases)"
    );
  }
  const text = phrases
    .map((p) =>
      p && typeof (p as { text?: unknown }).text === "string" ? (p as { text: string }).text : ""
    )
    .join(" ")
    .trim();

  return Response.json({ text }, { headers: { ...CORS_HEADERS } });
}

export async function handleAzureTranscription(
  providerConfig: AudioProvider,
  file: Blob & { name?: unknown },
  _modelId: string | null,
  token: string | null,
  formData: FormData,
  credentials: TranscriptionCredentials | null
) {
  const validated = validateAzureUpload(file, credentials);
  if ("errorResponse" in validated) return validated.errorResponse;
  const { region } = validated;

  const languageValue = formData.get("language");
  const locale =
    typeof languageValue === "string" && languageValue.trim()
      ? languageValue.trim()
      : AZURE_DEFAULT_LOCALE;

  const definition = JSON.stringify({
    locales: [locale],
    enhancedMode: { enabled: true, model: "MAI-Transcribe-2" },
    phraseList: { phrases: AZURE_PHRASE_HINTS },
  });

  // MAI-Transcribe-2 only accepts WAV/MP3/FLAC — normalize anything else
  // (webm/ogg/mp4, i.e. real browser MediaRecorder output) to WAV before
  // it reaches Azure. Native formats pass through unchanged: same bytes,
  // same filename/Content-Type, zero added latency.
  const uploadedType = (file.type || "").toLowerCase();
  let uploadFile: Blob & { name?: unknown } = file;
  if (!isAzureMaiNativeMime(uploadedType)) {
    const inputBytes = new Uint8Array(await file.arrayBuffer());
    const normalized = await normalizeForAzureMai(inputBytes);
    if ("error" in normalized) {
      return errorResponse(422, `Unable to normalize audio for Azure Speech: ${normalized.error}`);
    }
    // Copy into an ArrayBuffer-backed view: BlobPart excludes SharedArrayBuffer,
    // while Node's generic Uint8Array input is typed as ArrayBufferLike.
    const wavBytes = Uint8Array.from(normalized.bytes);
    const wavBlob = new Blob([wavBytes.buffer], { type: "audio/wav" }) as Blob & {
      name?: unknown;
    };
    wavBlob.name = "audio.wav";
    uploadFile = wavBlob;
  }

  const { body, contentType } = await buildMultipartBody(uploadFile, { definition }, "audio");
  const url = `https://${region}.api.cognitive.microsoft.com/speechtotext/transcriptions:transcribe?api-version=2025-10-15`;
  const headers = { ...buildAuthHeaders(providerConfig, token), "Content-Type": contentType };

  const fetched = await fetchAzureTranscription(url, headers, body);
  if ("errorResponse" in fetched) return fetched.errorResponse;

  if (!fetched.response.ok) {
    return upstreamErrorResponse(fetched.response, await fetched.response.text());
  }
  return parseAzureTranscriptionResponse(fetched.response);
}
